### ISSUE TITLE
Project not working 

### ISSUE THREAD

**Issue by EHSANKHAN786** [techinfo-youtube/house-marketplace-react-firebase#1]
I want to add some more feature in that to make your project as much as I can make BUT THE MAIN PROBLEM is I had just simply taken your project from the GitHub and it's not working means the content of your project is not showing on the browser so please just WhatsApp me on this number 
+13156441028

**Comment by techinfo-youtube** [comment]
you have to install project dependencies and configure env variables then only it works

**Comment by EHSANKHAN786** [comment]
So how to install dependencies and configuration please tell me
